name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: checkout
        uses: actions/checkout@v2

      - run: go version

      - name: go test
        run: go test ./... -v
